set-option -g default-shell "/bin/zsh"
set-option -g status-style bg=default

# set-window-option -g window-status-style fg='#333333',bg=default
# set-window-option -g window-status-current-style fg='#eeeeee',bg=default

set -g status-interval 1
set -g status-left ''
set -g status-right ''
set -g status-justify centre
set -g status-justify left
set -g prefix C-b
set -g base-index 1
set -g history-limit 100000
set -g default-terminal "xterm-256color"
set -g default-terminal "tmux-256color"
set -g default-terminal "screen-256color"
set -g terminal-overrides "xterm-256color"
set -ga terminal-overrides "xterm-256color:Tc"
set -as terminal-features ",xterm-256color:RGB"

bind -r C-k resize-pane -U
bind -r C-j resize-pane -D
bind -r C-h resize-pane -L
bind -r C-l resize-pane -R

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

set -g @catppuccin_flavor "mocha"
#set -g @catppuccin_flavor "latte"
#set -g @catppuccin_window_status_style "rounded"
#set -g @catppuccin_window_left_separator ""
#set -g @catppuccin_window_right_separator " "
#set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_status_modules_right "directory session"
#set -g @catppuccin_status_left_separator  " "
#set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

run '~/.tmux/plugins/tpm/tpm'
