[colors.bright]
black = "#637777"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#addb67"
magenta = "#c792ea"
red = "#ff5874"
# white = "#aaaaaa"
white = "#eeeeee"
yellow = "#f78c6c"

[colors.normal]
black = "#0F1418"
blue = "#82aaff"
cyan = "#7fdbca"
green = "#addb67"
magenta = "#c792ea"
red = "#ff5874"
#white = "#aaaaaa"
white = "#eeeeee"
yellow = "#f78c6c"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[cursor]
blink_interval = 800
style = "Block"

[font]
size = 16.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "full"
opacity = 0.93

[window.dimensions]
columns = 122
lines = 35

[window.padding]
x = 0
y = 0
